# Generated by Django 2.2.9 on 2023-02-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230208_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
